---

repos:
- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v2.2.3
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/PyCQA/isort.git
  rev: 5.10.1
  hooks:
  - id: isort
    args:
    - --honor-noqa

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.3.0
  hooks:
  - id: remove-tabs

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.3.0
  hooks:
  # Side-effects:
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  # Non-modifying checks:
  - id: name-tests-test
    files: >-
      ^tests/[^_].*\.py$
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: detect-private-key
  # Heavy checks:
  - id: check-ast
  - id: debug-statements
    language_version: python3

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.27.1
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types:
    - file
    - yaml
    args:
    - --strict

- repo: https://github.com/PyCQA/flake8.git
  rev: 5.0.4
  hooks:
  - id: flake8
    alias: flake8-no-wps
    name: flake8 WPS-excluded
    args:
    - --ignore
    - >-
      D100,
      D101,
      D103,
      D107,
      E402,
      E501,
    additional_dependencies:
    - flake8-2020 ~= 1.7.0
    - flake8-docstrings ~= 1.6.0
    - flake8-pytest-style ~= 1.6.0
    language_version: python3

- repo: https://github.com/PyCQA/flake8.git
  # NOTE: This is kept at v4 for until WPS starts supporting flake v5.
  # NOTE: Pre-commit.ci's autoupdate changes must be reverted to keep
  # NOTE: it working.
  # Ref: https://github.com/pre-commit-ci/issues/issues/83
  rev: 4.0.1
  hooks:
  - id: flake8
    alias: flake8-only-wps
    name: flake8 WPS-only
    args:
    - --ignore
    - >-
      WPS111,
      WPS347,
      WPS360,
      WPS422,
      WPS433,
      WPS437,
      WPS440,
      WPS441,
      WPS453,
    - --select
    - WPS
    additional_dependencies:
    - wemake-python-styleguide ~= 0.16.1
    language_version: python3

- repo: https://github.com/PyCQA/pylint.git
  rev: v2.14.5
  hooks:
  - id: pylint
    args:
    - --disable
    - >-
      import-error,
      invalid-name,
      line-too-long,
      missing-class-docstring,
      missing-function-docstring,
      missing-module-docstring,
      protected-access,
      super-init-not-called,
      unused-argument,
      wrong-import-position,
    - --output-format
    - colorized

...
